using System;
using System.IO;
using System.Text;
using attainment.Models;
using System.Linq;
using UglyToad.PdfPig;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace attainment.Infrastructure;

public interface IPdf
{
    public string Convert(FileInfo file);
    public string ExportExam(Exam exam, string? targetPath = null);
}

public class Pdf: IPdf
{
    public string Convert(FileInfo file)
    {
        if (!file.Exists)
            throw new FileNotFoundException($"PDF file not found: {file.FullName}");

        var text = new StringBuilder();

        using (var document = PdfDocument.Open(file.FullName))
        {
            foreach (var page in document.GetPages())
            {
                text.AppendLine(page.Text);
            }
        }

        return text.ToString();
    }

    public string ExportExam(Exam exam, string? targetPath = null)
    {
        if (exam == null || exam.Questions == null || exam.Questions.Length == 0)
            throw new ArgumentException("Exam must contain at least one question.", nameof(exam));

        // Determine target path (Downloads by default)
        var downloads = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Downloads");
        Directory.CreateDirectory(downloads);
        var filePath = targetPath;
        if (string.IsNullOrWhiteSpace(filePath))
        {
            var fileName = $"Exam_{DateTime.Now:yyyyMMdd_HHmmss}.pdf";
            filePath = Path.Combine(downloads, fileName);
        }
        else
        {
            var dir = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        }

        // Configure QuestPDF (ensure license-compatible setting)
        QuestPDF.Settings.License = LicenseType.Community;
#if DEBUG
        // Help diagnose potential layout issues during development
        QuestPDF.Settings.EnableDebugging = true;
#endif

        // Build the PDF document
        var doc = Document.Create(container =>
        {
            // QUESTIONS PAGE(S)
            container.Page(page =>
            {
                page.Margin(40);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(12));

                // Keep header simple to avoid conflicting constraints
                page.Header().Text("Exam").SemiBold().FontSize(20).FontColor(Colors.Blue.Medium);

                page.Content().Column(col =>
                {
                    for (int i = 0; i < exam.Questions.Length; i++)
                    {
                        var q = exam.Questions[i];
                        var idx = i + 1;

                        col.Item().PaddingBottom(10).Element(e =>
                            e.Column(inner =>
                            {
                                inner.Item().Text(txt =>
                                {
                                    txt.Span($"{idx}. ").SemiBold();
                                    txt.Span(Safe(q.Content)).WrapAnywhere();
                                });

                                inner.Item().Column(optionsCol =>
                                {
                                    foreach (var opt in q.Options)
                                    {
                                        optionsCol.Item().Text(t =>
                                        {
                                            t.Span($"   [{opt.Number}] ").SemiBold();
                                            t.Span(Safe(opt.Content)).WrapAnywhere();
                                        });
                                    }
                                });
                            })
                        );

                        // Divider between questions
                        col.Item().PaddingTop(4).BorderBottom(1).BorderColor(Colors.Grey.Lighten2);
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Attainment • ");
                    text.CurrentPageNumber();
                    text.Span("/");
                    text.TotalPages();
                });
            });

            // ANSWERS PAGE(S)
            container.Page(page =>
            {
                page.Margin(40);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header().Text("Answers & Explanations").SemiBold().FontSize(18).FontColor(Colors.Green.Darken2);

                page.Content().Column(ansCol =>
                {
                    for (int i = 0; i < exam.Questions.Length; i++)
                    {
                        var q = exam.Questions[i];
                        var correct = q.Options.FirstOrDefault(o => o.Number == q.CorrectOption);
                        var correctText = correct?.Content ?? string.Empty;

                        ansCol.Item().PaddingBottom(8).Element(e =>
                            e.Column(inner =>
                            {
                                inner.Item().Text(t =>
                                {
                                    t.Span($"Q{i + 1}: ").SemiBold();
                                    t.Span(Safe(q.Content)).WrapAnywhere();
                                });
                                inner.Item().Text(t =>
                                {
                                    t.Span("Correct Answer: ").SemiBold();
                                    t.Span($"[{q.CorrectOption}] {Safe(correctText)}").FontColor(Colors.Blue.Darken2).WrapAnywhere();
                                });
                                inner.Item().Text(t =>
                                {
                                    t.Span("Explanation: ").SemiBold();
                                    t.Span(Safe(q.Explanation)).FontColor(Colors.Grey.Darken2).WrapAnywhere();
                                });
                            })
                        );
                        ansCol.Item().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(4);
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Attainment • ");
                    text.CurrentPageNumber();
                    text.Span("/");
                    text.TotalPages();
                });
            });
        });

        // Local helper to sanitize null/empty text
        static string Safe(string? value) => string.IsNullOrWhiteSpace(value) ? "-" : value;

        doc.GeneratePdf(filePath);
        return filePath!;
    }
}